name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0"]
        rails: ["5.0", "5.1", "5.2", "6.0", "6.1"]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/rails_${{ matrix.rails }}.gemfile" bundle install

    - name: Rubocop
      run: "ruby -e \"RUBY_VERSION == '3.0.0' ? system('bundle exec rubocop') : exit(0)\""

    - name: Tests
      run: bundle exec rake spec
